Learn.MyContacts.MVC/Models/ErrorViewModel.cs
using System;

namespace Learn.MyContacts.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Learn.MyContacts.MVC/Controllers/ContactEmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Learn.MyContacts.MVC.Controllers
{
    [Produces("application/json")]
    [Route("api/ContactEmail")]
    public class ContactEmailController : Controller
    {
        //// GET: api/ContactEmail
        //[HttpGet]
        //public IEnumerable<string> Get()
        //{
        //    return new string[] { "value1", "value2" };
        //}

        // GET: api/ContactEmail/5
        [HttpGet("{id}", Name = "Get")]
        public string Get(int id)
        {
            return "value";
        }
        
        // POST: api/ContactEmail
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }
        
        // PUT: api/ContactEmail/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }
        
        // DELETE: api/ApiWithActions/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

Learn.MyContacts.MVC/Controllers/ContactPhoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Learn.MyContacts.Models;
using Learn.MyContacts.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Learn.MyContacts.MVC.Controllers
{
  
    public class ContactPhoneController : Controller
    {
        private readonly IContactCollGenericService<ContactPhone> _service;

        public ContactPhoneController(IContactCollGenericService<ContactPhone> service)
        {
            _service = service;
        }

        // GET: api/ContactPhone/5
        [HttpGet]
        public async Task<JsonResult> GetContactPhoneByID(int id)
        {
            var cp = await _service.GetByID(id);
            return Json(cp);
        }
        // GET: api/ContactPhone/5
        [HttpGet]
        public async Task<JsonResult> GetContactPhoneByContactID(int id)
        {
            var cps = await _service.GetAll(id);
            return Json(cps);
        }

        [HttpPost]
        public async Task<IActionResult> Save([FromBody] ContactPhone cp)
        {
            cp.ContactPhoneID = await _service.Save(cp);
            return Json(cp);
        }
        

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            return Json(await _service.Delete(id));
        }

    }
}

Learn.MyContacts.MVC/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Learn.MyContacts.Models;
using Learn.MyContacts.Repository;
using Learn.MyContacts.Services;

namespace Learn.MyContacts.MVC.Controllers
{
    public class ContactsController : Controller
    {
        private readonly IContactService _service;

        public ContactsController(IContactService service)
        {
            _service = service;
        }

        // GET: Contacts
        public async Task<IActionResult> Index()
        {
            var result = await _service.GetAll(); 
            return View(result);
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _service.GetByID(id.Value);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContactID,Name,Address,Company")] Contact contact)
        {
            if (ModelState.IsValid)
            {
                contact.ContactID= await _service.Save(contact);
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _service.GetByID(id.Value);
            if (contact == null)
            {
                return NotFound();
            }
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContactID,Name,Address,Company")] Contact contact)
        {
            if (id != contact.ContactID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    contact.ContactID = await _service.Save(contact);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this._service.Exists( contact.ContactID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _service.GetByID(id.Value);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _service.GetByID(id);
            contact.ContactID = await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }

       
    }
}

Learn.MyContacts.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Learn.MyContacts.MVC.Models;

namespace Learn.MyContacts.MVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Learn.MyContacts.MVC/Views/Contacts/Create.cshtml
@model Learn.MyContacts.Models.Contact

@{
    ViewData["Title"] = "Create";
}

<h2>Criar Contato na Agenda</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nome do Contato</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label">Endereço</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label">Empresa</label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar Contato" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar para a Agenda</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Learn.MyContacts.MVC/Views/Contacts/Delete.cshtml
@model Learn.MyContacts.Models.Contact

@{
    ViewData["Title"] = "Delete";
}

<h2>Deletar Contato da Agenda</h2>

<h3>Você tem certeza que deseja deletar este contato?</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ContactID" />
        <input type="submit" value="Deletar" class="btn btn-default" /> |
        <a asp-action="Index">Retornar para a Agenda</a>
    </form>
</div>

Learn.MyContacts.MVC/Views/Contacts/Edit.cshtml
@model Learn.MyContacts.Models.Contact

@{
    ViewData["Title"] = "Edit";
}

<h2>Editar Contato na Agenda</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContactID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label" ></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar para a Agenda</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Learn.MyContacts.MVC/Views/Contacts/Index.cshtml
@model IEnumerable<Learn.MyContacts.Models.Contact>

@{
    ViewData["Title"] = "Index";
}

<h2>Agenda de Contatos</h2>

<p>
    <a asp-action="Create">Novo Contato</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Company)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ContactID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ContactID">Ver Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.ContactID">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Learn.MyContacts.MVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Sobre";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p> Eduardo Bariquello</p>
<p> C#/ASP.NET MVC/SharePoint Architect</p>
<p> Mobile: 11981956008</p>
<p> Mail: ebariquello@hotmail.com</p>

Learn.MyContacts.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="jumbotron">
    <h1Agenda - EVO</h1>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Bem-Vindo à Agenda - EVO</h2>
        <p>
            Agenda - EVO é uma aplicação exemplo que
            demonstra como usar o Entity Framework Core em uma
            aplicação ASP.NET Core MVC web application.
            Para iniciar a aplicação  <a asp-area="" asp-controller="Contacts" asp-action="Index">clique aqui </a>
        </p>
    </div>
 
</div>

Learn.MyContacts.MVC/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agenda - EVO</title>
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Agenda - EVO</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Sobre</a></li>
                    <li><a asp-area="" asp-controller="Contacts" asp-action="Index">Agenda - EVO </a></li>
                  
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Agenda - EVO</p>
        </footer>
    </div>
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>